---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aap-controller-token
  namespace: ztp-day2-automation
  labels:
    cluster.open-cluster-management.io/type: ans
    cluster.open-cluster-management.io/credentials: ""
stringData:
  host: aap_controller_url         # <- variable provided by admin
  token: token_goes_here           # <- variable provided by admin
